name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  test_build:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
      REPO: frontend
    steps:
    - uses: actions/checkout@v2

    # Set up  node
    - uses: actions/setup-node@v1
      with:
        node-version: '4.x'

    - run: npm install
    
    - name: Build
      run: ./scripts/build.sh

    - name: Unit test
      run: ./scripts/unit_test.sh

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: coverage/coverage.json

    - name: Push catalogue to Docker Hub
      run: | 
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        docker push lautibringas/frontend

  sonarCloudTrigger:
    needs: test_build
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@master
      - name: Download code coverage results
        uses: actions/download-artifact@v1
        with:
          name: code-coverage-report
          path: bin
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
  
  deploy_staging:
    needs: test_build
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
      STAGING_KUBERNETES_KUBECONFIG: ${{ secrets.STAGING_KUBERNETES_KUBECONFIG }}
      PRODU_KUBERNETES_KUBECONFIG: ${{ secrets.PRODU_KUBERNETES_KUBECONFIG }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
    
      - name: Get kubectl
        uses: azure/setup-kubectl@v1
    
      - name: Deploy to staging
        run: ./deploy/deploy_staging.sh

  integration_test:
    needs: deploy_staging
    runs-on: ubuntu-latest
    env:
      CYPRESS_baseUrl: ${{secrets.STAGING_CLUSTER_IP}}
    steps:
      - uses: actions/checkout@v2
      - run: sleep 20

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          project: test/e2e-tests-socks